### PR TITLE
Adds configuration + documentation for iterm2

### PR DESCRIPTION
**Pull request by paulmcarrier**
Adds configuration + documentation for iterm2

### CODE REVIEW

**Comment by paulmcarrier** [comment]
Thanks for a great colorscheme! I wanted to help out by adding a config for iTerm2!

**Comment by mngshm** [comment]
Ahh, finally iterm2 port. Always wanted to port everblush to MacOS apps. You can try contributing more for sure :D

**Comment by mngshm** [comment]
Well can you also post a good screenshot in the src/iterm2 Readme? ? With some round and shadowed style ?

**Comment by paulmcarrier** [comment]
@Mangeshrex Will do!

**Comment by mngshm** [comment]
Cool

**Pull request merged**
